### ISSUE TITLE
Help needed to run this Ctakes-Rest-Service

### ISSUE THREAD

**Issue by swagat123** [gandhirajan/cTAKES#1]
Hi @gandhirajan  , I want to run this Ctakes-Rest-Service. I would like to know a little bit more information how to run this.I am quite new to this cTakes and Java.

1) Make the code changes available under https://github.com/gandhirajan/cTAKES/tree/master/SpringUpgrade/ctakes-SVN-src to upgrades
   cTAKES to Spring 4x as it currently uses Spring 3x -- here what actually needs to be changed. 
2) Build all cTAKES modules and copy all ctakes module JARS to the repo folder in the webapp 
-- which cTAKES modules and under which folder. where to find the jar files that is to be copied in repo folder.Where is the webapp folder in repo folder?
3. will create war file by pointing to directory 
<path>\cTAKES\cTakes-Rest-Service>mvn package -- is it the correct one?

Thanks
swagat

**Comment by gandhirajan** [comment]
Hi, That was a bit old implementation of ctakes rest service. The latest implementation is available under https://github.com/GoTeamEpsilon/ctakes-rest-service/tree/master/ctakes-web-rest

**Comment by swagat123** [comment]
Thank you.
