### ISSUE TITLE
ICD 10 Dictionary

### ISSUE THREAD

**Issue by premanandmanimaran** [gandhirajan/cTAKES#2]
@gandhirajan 

Hi How are you? 

I am currently looking for some support on the Ctakes project. 
Are you from chennai?
Can you help?

**Comment by gandhirajan** [comment]
@premanandmanimaran  hi, i m good. I m located in Bangalore and from Madurai. What support you are looking for? What are you trying to achieve?

**Comment by gandhirajan** [comment]
Since there is no issue description, I m closing this.

**Comment by premanandmanimaran** [comment]
@gandhirajan 

I am looking for Training and Project support for my Team.
Can you share you email and Mobile number?
So i can reach out to you?

**Comment by gandhirajan** [comment]
@premanandmanimaran  you can mail me on gandhirajan<dot>n@gmail.com

**Comment by gandhirajan** [comment]
@premanandmanimaran  Leave me a message here - https://www.linkedin.com/in/gandhirajann/
