### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by BavithraRamesh** [gandhirajan/cTAKES#27]
I build the code and it generated war file but I am having error while deploying in corsfilter.I can't able to deploy your code.Kindly request you to provide me the steps to start this Ctakes api

**Comment by gandhirajan** [comment]
Hi @BavithraRamesh , this code is merged into official cTAKES codebase - https://svn.apache.org/repos/asf/ctakes/trunk/ctakes-web-rest/ that has corsfilter settings as well. Email me for more info.

**Comment by BavithraRamesh** [comment]
Thanks for your reply Sir but I try to get the code from SVN it ask me fr password Sir
