### ISSUE TITLE
Annotation Response not coming in the API Response

### ISSUE THREAD

**Issue by ChaithanyaShree** [gandhirajan/cTAKES#31]
Dear GandhiRajan,
                          Hi This is Chaithanya. I am trying your Ctakes-web-rest project. I got the output in that API Response. But for me StrengthAnnotation,DrugchangeStatus Annotation,StrengthAnnotation,FractionStrengthAnnotation,FrequencyUnitAnnotation is not there in that API Response. How to enable this annotation. I need to add anything in that code. And one more thing I tried your github link code also for that I got Text analysed successful message with empty response json. I want to fix this issue. Please advice. Awaiting your reply.

Thanks,
Chaithanya

**Comment by ChaithanyaShree** [comment]
Dear Gandhi Rajan,
                      Can you please help to fix this issue

Thanks,
Chaithanya

**Comment by gandhirajan** [comment]
@ChaithanyaShree  to get other annotation details you might have to make changes in the piper files... for blank response we need to check at the server logs. Mail me for more details.

**Comment by gandhirajan** [comment]
No detailed info from the reporter after reaching out on email. No traction from the user.
